[config]
version_check = false

[config.hooks]
after = ['fish ~/.config/uchiha/colors/fish-colors.fish']

[templates.m3colors]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.config/uchiha/colors/colors.json'

[templates.hyprland_colors]
input_path = '~/.config/matugen/templates/hyprland/hyprland-colors.conf'
output_path = '~/.config/uchiha/colors/colors.conf'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprland/hyprlock-colors.conf'
output_path = '~/.config/uchiha/colors/hyprlock-colors.conf'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

#[templates.kde_colors]
#input_path = '~/.config/matugen/templates/kde/color.txt'
#output_path = '~/.config/uchiha/colors/color.txt'

[templates.wallpaper]
input_path = '~/.config/matugen/templates/wallpaper.txt'
output_path = '~/.config/uchiha/colors/path.txt'

[templates.kitty]
input_path = '~/.config/matugen/templates/Kitty/colors-kitty.conf'
output_path = '~/.config/uchiha/colors/colors-kitty.conf'

[templates.kvantum]
input_path = '~/.config/matugen/templates/kvantum/KvGlass.kvconfig'
output_path = '~/.config/Kvantum/KvGlassMatugen/KvGlassMatugen.kvconfig'

[templates.kvantum_svg]
input_path = '~/.config/matugen/templates/kvantum/KvGlass.svg'
output_path = '~/.config/Kvantum/KvGlassMatugen/KvGlassMatugen.svg'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors/matugen.rasi'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors-waybar.css'
output_path = '~/.config/uchiha/colors/colors-waybar.css'

[templates.fish]
input_path = '~/.config/matugen/templates/fish-sequences.txt'
output_path = '~/.config/uchiha/colors/fish-sequences.txt'

[templates.fish_colors]
input_path  = '~/.config/matugen/templates/fish-colors.fish'
output_path = '~/.config/uchiha/colors/fish-colors.fish'
